### ISSUE TITLE
Add bulk API endpoints

### ISSUE THREAD

**Issue by k88hudson** [mozilla/api.webmaker.org#76]
We would like to be able to update, create, and delete several pages/elements at once.

For updates/creates, each page or element should be able to have different update objects.

@cadecairos is that enough detail?

**Comment by thisandagain** [comment]
Could you provide an example endpoint and JSON payload as an example?

**Comment by k88hudson** [comment]
Basically for `.../projects/:project/pages` and `...pages/:page/elements`, i need to be able to send multiple `GET`/`PATCH`/`DELETE` requests.

That could work with something like this  (from https://github.com/hapijs/bassmaster)
```
POST /batch
{ "requests": [
    {"method": "patch", "path": "/users/1/projects/23/pages/12", "payload": "{...}"},
    {"method": "get", "path": "/users/1/projects/23/pages/14"}
] }
```

or this

```
PATCH /users/1/projects/12/pages
[
  {id: '12', title: 'foo', style: ... }, // update
  {id: '14', deleted: true}, // delete
  {title: 'bar}, // create
]
```

**Comment by k88hudson** [comment]
@ashleygwilliams had some thoughts about this

**Comment by cadecairos** [comment]
woah, bassmaster looks pretty cool.

**Comment by cadecairos** [comment]
So Bassmaster works great, except when you want to refer to a value nested within a response object when pipelining.

for example, the response after creating a project is:

```
{
  status: 'created',
  project: { /* project data */},
  page: { /* page data */}
}
```

if you wanted to create a page in a batch request for that new project, you'd want to set the batch requests path to  `/users/{user}/project/$0.project.id/pages`, but unfortunately Bassmaster won't look past the root response object for values.

**Comment by cadecairos** [comment]
I filed this upstream: https://github.com/hapijs/bassmaster/issues/50

**Comment by cadecairos** [comment]
So, I've become the maintainer of hapijs/bassmaster

There's a few things that need attention, then I'll tag and ship 1.8.0

**Comment by cadecairos** [comment]
So here's how I see this endpoint being used by webamker-app

Webmaker app will need to maintain an array of actions/changes to projects/pages/elements that require api calls to be persisted. If an ID for an edit is not known (i.e. the create call in the API is part of a previous action) you must use "pipelining" to grab the id from that create calls response. Here's an example:

```js
{
  "requests" : [
    {
      "method": "post",
      "path": "/users/1/projects",
      "payload": { /* project data */ }
    },
    {
      "method": "post",
      // use Hoek.reach syntax to get the id attribute out of the response body from the 0th request in the requests array
      "path": "/users/1/projects/$0.project.id/pages",
      "payload": { /* page data */ }
    },
    {
      "method": "post",
      // same deal here, but also get the new page id from the request at the first index of the requests array
      "path": "/users/1/projects/$0.project.id/pages/$1.page.id/elements",
      "payload": { /* element data */ }
    }
  ]
}
```

**Comment by Pomax** [comment]
this feels like it's going to need a good failure mechanics as part of the request, too, and probably an atomic indicator, to indicate which parts are a transaction (if any part fails, roll back the entire transaction set) and which parts are one offs. If the second post in your example fails, for instance, should the project creation be rolled back too? (I would argue 'yes').

**Comment by cadecairos** [comment]
The plugin that enables the example I gave won't allow us to do any transactions.  This is because it's calling each route independently using inject. If we want transactions we'll need to build a bulk endpoint from scratch.

**Comment by Pomax** [comment]
hmm, we could write a middleware that looks at the result of each request, with our own rollback on top, so we don't need a full "from scratch" endpoint, perhaps?

**Comment by cadecairos** [comment]
bassmaster doesn't currently provide a mechanism for adding any prerequisites or tails, And I'm not sure I should add something to it just to serve our own cause..

**Comment by cadecairos** [comment]
we could add an event listener that looks specifically for completed batch requests and checks if anything failed, then reverses them... Not sure quite how janky that will be.

**Comment by toolness** [comment]
I agree with Pomax that as much of the transaction as possible should be rolled-back by the server, rather than by the client. Leaving rollbacks to the client means that a lot of requests will likely remain unresolved (if the user is on a spotty internet connection, the app crashes, etc), which could then result in a lot more potential states that the DB could be in, which clients would then have to check for and/or keep bookkeeping information about before making requests. DB transactions vastly simplify our solution space by minimizing the number of possible states our DB can be in... but I'm also just jumping into this issue now and lack a lot of context, so I could be wrong.

> bassmaster doesn't currently provide a mechanism for adding any prerequisites or tails, And I'm not sure I should add something to it just to serve our own cause..

I'm not familiar at all with bassmaster, or even hapi for that matter, but I'd argue that (A) the need to encapsulate a series of API calls within a transaction is almost certainly a very big use case in general, and (B) a generic mechanism like prereqs/tails or before/after could potentially be useful for more than just transactions. For instance, what if you wanted to record metrics on how long a batch call took?

> we could add an event listener that looks specifically for completed batch requests and checks if anything failed, then reverses them... Not sure quite how janky that will be.

One disadvantage of this approach over the transactional one is that because it's not atomic, it still potentially leaves the DB in an inconsistent state, albeit for a very short period of time.

**Comment by cadecairos** [comment]
I'm all for making the bulk endpoint transactional, but I don't think bassmaster is the appropriate tool to make it happen with, based on how it operates. It's injecting individual requests to the hapi server, meaning even if we modified bassmaster to let us hook in before and after, we'd need to have some complicated way for each request to determine if it's part of a bulk request and needs to execute its' query as part of a transaction.

I think we just need an endpoint that takes a json array of actions and data, and attempts to execute the actions one by one, as a transaction. 

```
{actions: [
  { method: 'create', type: 'project', data: {...} },
  { method: 'update, type: 'page', data: { id: "$0.page.id", ... }
]}
```

**Comment by toolness** [comment]
Oh weird, I guess I was just thinking of this in terms of raw SQL, where you could just issue `BEGIN TRANSACTION` at the beginning, then issue any SQL like you would normally, and then issue `COMMIT`... i.e., each request wouldn't actually need to know or care whether it was part of a transaction, largely thanks to [isolation](https://en.wikipedia.org/wiki/ACID#Isolation) (I think... I am soooo rusty on databases).

Anyways, your JSON array endpoint also sounds great to me... um, I think. I wish Github's REST API had that exact thing, actually, which makes me wonder why they don't already... perhaps it's weirdly susceptible to some sort of abuse?

**Comment by toolness** [comment]
Oh wait, is that [sample JSON payload](https://github.com/mozilla/api.webmaker.org/issues/76#issuecomment-120504264) something that'd be part of a client's request to api.webmaker.org, or is it part of some kind of funky hapi route definition on the server-side?

**Comment by cadecairos** [comment]
that sample would be part of the client request.

begin/commit will not work, because each request uses a separate connection to the database.

**Comment by toolness** [comment]
ahhh got it, cool. yeah the JSON array endpoint sounds great to me!

**Comment by cadecairos** [comment]
I'm not entirely sure how to define unknowns (like unique ids for yet-to-be-created database objects) and replace them with the ids as they become available.

in the sample json above, we won't know the page id of the project because it doesn't exist yet. We do know that it will be in the response data after creating a project. The server could walk each request before executing and substitute values in like bassmaster does with Hoek.reach.

**Comment by k88hudson** [comment]
How does the server respond when a partial failure occurs?
